import Link from 'next/link';
import { getBooks, getMeetings } from '@/features/catalog/queries';
import { BookCard } from '@/components/book-card';

export default async function HomePage() {
  const [books, meetings] = await Promise.all([getBooks(), getMeetings()]);
  return <>
    <section className="hero"><div className="hero-inner"><div className="hero-copy"><span className="eyebrow">Leitura com mais companhia</span><h1>Tem histórias que ficam melhores <em>juntas.</em></h1><p>Um clube para descobrir livros, dividir impressões e encontrar gente que sente cada capítulo de um jeito só dela.</p><div className="hero-actions"><Link className="button" href="/livros">Descobrir leituras <span aria-hidden="true">↗</span></Link><Link className="button button-dark" href="/comunidade">Conhecer a comunidade</Link></div><p className="hero-note">Um capítulo de cada vez. No seu ritmo, do seu jeito.</p></div><div className="hero-art" aria-label="Uma capa de livro ilustrada em meio a formas geométricas"><div className="orbit"/><span className="hero-dot"/><div className="book-stack"><div className="book-cover"><span className="book-cover-kicker">uma história compartilhada</span><span className="book-cover-title">Entre<br/>páginas<br/>e encontros</span><span className="book-cover-author">DIyspur · CLUBE DE LEITURA</span></div></div><div className="floating-chip chip-a"><strong>um clube</strong> feito de leitores</div><div className="floating-chip chip-b">Leia. <strong>Converse.</strong> Descubra.</div></div></div></section>
    <section className="section container"><div className="section-head"><div><span className="eyebrow">A biblioteca</span><h2>Histórias para encontrar</h2><p>Um bom livro abre conversa — e aqui a conversa continua.</p></div><Link className="text-link" href="/livros">Ver todos os livros <span aria-hidden="true">→</span></Link></div>{books.length ? (books.length === 1 ? <div className="featured-book"><BookCard book={books[0]} /></div> : <div className="book-grid">{books.slice(0,4).map((book) => <BookCard key={book.id} book={book}/>)}</div>) : <div className="empty-state"><div className="empty-state-mark" aria-hidden="true">✳</div><h3>Novas histórias estão a caminho</h3><p>Estamos preparando a próxima seleção do clube. Enquanto isso, venha conhecer os leitores e as conversas que já estão acontecendo.</p><div className="empty-actions"><Link className="button button-dark button-small" href="/comunidade">Explorar a comunidade</Link></div></div>}</section>
    <section className="section container"><div className="section-head"><div><span className="eyebrow">Perto de acontecer</span><h2>Próximos encontros</h2><p>Conversas ao vivo sobre livros, ideias e tudo o que ficou nas entrelinhas.</p></div><Link className="text-link" href="/calendario">Abrir calendário →</Link></div>{meetings.length ? <div className="meeting-list">{meetings.slice(0,2).map((meeting) => <Link className="meeting-row" key={meeting.id} href="/calendario"><div><h3>{meeting.title}</h3><p>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'full',timeStyle:'short'}).format(new Date(meeting.scheduled_at))}</p></div><span className="status-pill">{meeting.status === 'live' ? 'AO VIVO' : 'Encontro'}</span></Link>)}</div> : <div className="notice">A agenda do próximo ciclo será anunciada em breve. <Link className="text-link" href="/calendario">Acompanhe por aqui →</Link></div>}</section>
    <section className="section container"><div className="feature-panel"><div className="feature-cover" aria-hidden="true"><span className="cover-placeholder">Cada leitura<br/>abre uma porta.</span></div><div><span className="eyebrow">Mais que virar páginas</span><h3>Uma história é só o começo.</h3><p>Leia no seu tempo. Traga suas perguntas. Descubra como outras pessoas viveram a mesma história — e faça parte da próxima conversa.</p><div className="feature-meta">Leitura compartilhada, sem pressa e sem respostas certas.</div><Link className="button button-small" href="/cadastro">Encontrar meu lugar <span aria-hidden="true">↗</span></Link></div></div></section>
  </>;
}
